# This file is a part of nyaastrap
# Licensed under GPLv3
version: "2"
services:
  build-rootfs:
    image: kreato/builder:latest
    volumes:
      - ./:/nyaa
      - ./out:/out
      - ./packages:/etc/nyaa.tarballs
  
  build-packages:
    image: ghcr.io/kreatolinux/builder:latest
    volumes:
      - ./:/nyaa
      - /etc/nyaa.tarballs:/etc/nyaa.tarballs
    command: /nyaa/src/nyaastrap/nyaastrap buildPackages  
