name: Build packages

on:
  workflow_dispatch:

jobs:
  build:
    #runs-on: self-hosted 
    runs-on: ubuntu-latest # Temporary
    container: ghcr.io/kreatolinux/builder:latest
    #volumes:
    #  - /etc/nyaa.tarballs:/etc/nyaa.tarballs 

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Cache built packages
        uses: actions/cache@v3
        with:
          path: /etc/nyaa.tarballs
          key: cache-nyaa-tarballs

      - name: Build packages
        run: |
          nimble install --depsOnly -Y
          nimble nyaastrap
          ./src/nyaastrap/nyaastrap buildPackages --useCacheIfAvailable=true --repo=/etc/nyaa

