name: Build rootfs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    container:
      image: alpine
    
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Cache built packages
        uses: actions/cache@v3
        with:
          path: /var/cache/kpkg/archives
          key: cache-nyaa-tarballs

      - name: Build nocc rootfs tarball
        run: |
          ln -s $GITHUB_WORKSPACE /work
          mkdir /out
          ln -s /out /work/out
          cd /work
          cat > /etc/apk/repositories << EOF; $(echo)

https://dl-cdn.alpinelinux.org/alpine/v$(cut -d'.' -f1,2 /etc/alpine-release)/main/
https://dl-cdn.alpinelinux.org/alpine/v$(cut -d'.' -f1,2 /etc/alpine-release)/community/
https://dl-cdn.alpinelinux.org/alpine/edge/testing/

EOF
          apk update
          apk add alpine-sdk
          apk add nimble
          make deps
          make kpkg
          ./out/kpkg update
          sed s/gcc/musl-gcc/g -i /etc/kpkg/kpkg.conf
          make kreastrap
          ./src/kreastrap/kreastrap rootfs --buildType=nocc --arch=amd64
          cd /out
          tar -czvf /work/kreato-linux-nocc-musl-"$(date +%d-%m-%Y)"-amd64.tar.gz *
       
      
      - name: Upload nocc Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: nocc-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-nocc-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error

      - name: Build builder rootfs tarball
        run: |
          cd /work
          rm -rf /out
          ./src/kreastrap/kreastrap rootfs --buildType=builder --arch=amd64
          cd /out
          tar -czvf /work/kreato-linux-builder-"$(date +%d-%m-%Y)"-amd64.tar.gz *
    
      - name: Upload Builder Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: builder-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-builder-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error 
          
      - name: Build server rootfs tarball
        run: |
          cd /work
          rm -rf /out
          ./src/kreastrap/kreastrap rootfs --buildType=server --arch=amd64
          cd /out
          tar -czvf /work/kreato-linux-builder-"$(date +%d-%m-%Y)"-amd64.tar.gz *
    
      - name: Upload Server Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: server-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-server-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error 
