name: Build rootfs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    container: 
      image: kreato/builder:latest
      volumes:
        - /var/cache/kpkg/archives:/var/cache/kpkg/archives 
    
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Cache built packages
        uses: actions/cache@v3
        with:
          path: /var/cache/kpkg/archives
          key: cache-nyaa-tarballs

      - name: Build nocc rootfs tarball
        run: |
          ln -s $GITHUB_WORKSPACE /work
          mkdir /out
          ln -s /out /work/out
          cd /work
          make deps
          make kreastrap
          ./src/kreastrap/kreastrap rootfs --buildType=nocc --arch=amd64
          cd /out
          tar -czvf /work/kreato-linux-nocc-"$(date +%d-%m-%Y)"-amd64.tar.gz *
       
      
      - name: Upload nocc Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: nocc-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-nocc-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error

      - name: Build builder rootfs tarball
        run: |
          cd /work
          ./out/kreastrap rootfs --buildType=builder --arch=amd64
          cd /out
          tar -czvf /work/kreato-linux-builder-"$(date +%d-%m-%Y)"-amd64.tar.gz *
    
      - name: Upload Builder Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: builder-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-builder-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error 
          
      - name: Build server rootfs tarball
        run: |
          cd /work
          ./out/kreastrap rootfs --buildType=server --arch=amd64
          cd /out
          tar -czvf /work/kreato-linux-builder-"$(date +%d-%m-%Y)"-amd64.tar.gz *
    
      - name: Upload Server Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: server-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-server-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error 
