name: Format Nim Files

on:
  push:
    paths:
      - '**.nim'
  pull_request:
    paths:
      - '**.nim'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
      - name: Run nimpretty
        uses: juancarlospaco/nimpretty-action@main
      - name: Commit Nimpretty Fixes
        uses: EndBug/add-and-commit@v5
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
